# Generated by Django 4.1.4 on 2023-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summariser', '0002_alter_audio_num_speakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='summary',
        ),
        migrations.AddField(
            model_name='audio',
            name='a_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='e_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='use_si',
            field=models.BooleanField(default=False),
        ),
    ]
